version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://server:3000
    depends_on:
      - server

networks:
  app-network: